[project]
name = "veel-internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.8",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
